# Generated by Django 3.1.dev20200122124522 on 2020-04-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('prenom_pere', models.CharField(max_length=50)),
                ('nom_pere', models.CharField(max_length=50)),
                ('profession_pere', models.CharField(max_length=50)),
                ('papier_pere', models.ImageField(upload_to='')),
                ('prenom_mere', models.CharField(max_length=50)),
                ('nom_mere', models.CharField(max_length=50)),
                ('profession_mere', models.CharField(max_length=50)),
                ('papier_mere', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Naissance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('prenom_pere', models.CharField(max_length=50)),
                ('nom_pere', models.CharField(max_length=50)),
                ('profession_pere', models.CharField(max_length=50)),
                ('papier_pere', models.ImageField(upload_to='')),
                ('prenom_mere', models.CharField(max_length=50)),
                ('nom_mere', models.CharField(max_length=50)),
                ('profession_mere', models.CharField(max_length=50)),
                ('papier_mere', models.CharField(max_length=50)),
            ],
        ),
    ]
