# Generated by Django 3.1.dev20200122124522 on 2020-04-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deces',
            name='papier_mere',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='naissance',
            name='papier_mere',
            field=models.ImageField(upload_to=''),
        ),
    ]
