# Generated by Django 3.1.dev20200122124522 on 2020-04-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200429_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deces',
            name='date',
        ),
        migrations.RemoveField(
            model_name='naissance',
            name='date',
        ),
        migrations.AddField(
            model_name='deces',
            name='types_piece_mere',
            field=models.CharField(choices=[('nina', 'Carte Nina'), ('identite', "Carte d'identité"), ('passport', 'passeport')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='deces',
            name='types_piece_pere',
            field=models.CharField(choices=[('nina', 'Carte Nina'), ('identite', "Carte d'identité"), ('passport', 'passeport')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='naissance',
            name='types_piece_mere',
            field=models.CharField(choices=[('nina', 'Carte Nina'), ('identite', "Carte d'identité"), ('passport', 'passeport')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='naissance',
            name='types_piece_pere',
            field=models.CharField(choices=[('nina', 'Carte Nina'), ('identite', "Carte d'identité"), ('passport', 'passeport')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='deces',
            name='nom',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='deces',
            name='nom_mere',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='deces',
            name='nom_pere',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='deces',
            name='prenom',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='deces',
            name='prenom_mere',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='deces',
            name='prenom_pere',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='deces',
            name='profession_mere',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='deces',
            name='profession_pere',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='naissance',
            name='nom',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='naissance',
            name='nom_mere',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='naissance',
            name='nom_pere',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='naissance',
            name='prenom',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='naissance',
            name='prenom_mere',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='naissance',
            name='prenom_pere',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='naissance',
            name='profession_mere',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='naissance',
            name='profession_pere',
            field=models.CharField(default='', max_length=50),
        ),
    ]
